name: CI/CD Pipeline for Backend

on:
  push:
    branches:
      - main

jobs:
  backend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 21 for Backend
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      - name: Build Backend with Maven
        run: |
          cd backend
          mvn clean install

      - name: Deploy Backend to Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            cd ~/projeto/backend
            git pull origin main
            mvn clean install
            sudo systemctl restart backend.service